[package]
name = "notation_tabs"
publish = false
version = "0.4.0"
description = "Fun notation - tabs"

edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
notation_tab = { workspace = true }